// ====================================================
// Common Component Prop Types

import { ReactNode } from 'react'

// ====================================================
export type CommonComponentsProps = {
  [key: string]: any
}
export type CommonComponentReturnType = ReactNode

// ====================================================
// Shared Component Prop Types
// ====================================================
export type * from './lib/Abbreviation'
export type * from './lib/Address'
export type * from './lib/Area'
export type * from './lib/Article'
export type * from './lib/Aside'
export type * from './lib/Audio'
export type * from './lib/Base'
export type * from './lib/BiDirectionalIsolation'
export type * from './lib/BiDirectionalOverride'
export type * from './lib/Division'
export type * from './lib/EmphasizedText'
export type * from './lib/Fieldset'
export type * from './lib/Figcaption'
export type * from './lib/Figure'
export type * from './lib/Footer'
export type * from './lib/Form'
export type * from './lib/Head'
export type * from './lib/Header'
export type * from './lib/Heading'
export type * from './lib/HeadingGroup'
export type * from './lib/HorizontalRule'
export type * from './lib/Html'
export type * from './lib/Hyperlink'
export type * from './lib/Iframe'
export type * from './lib/Image'
export type * from './lib/Input'
export type * from './lib/InsertedText'
export type * from './lib/Italic'
export type * from './lib/KeyboardInput'
export type * from './lib/Label'
export type * from './lib/Legend'
export type * from './lib/LineBreak'
export type * from './lib/Link'
export type * from './lib/List'
export type * from './lib/Main'
export type * from './lib/Map'
export type * from './lib/Mark'
export type * from './lib/Menu'
export type * from './lib/Meta'
export type * from './lib/Meter'
export type * from './lib/Navigation'
export type * from './lib/Noscript'
export type * from './lib/Optgroup'
export type * from './lib/Option'
export type * from './lib/OrderedList'
export type * from './lib/Output'
export type * from './lib/Paragraph'
export type * from './lib/Picture'
export type * from './lib/PreformattedText'
export type * from './lib/Progress'
export type * from './lib/Quote'
export type * from './lib/Ruby'
export type * from './lib/RubyParentheses'
export type * from './lib/RubyText'
export type * from './lib/Sample'
export type * from './lib/Script'
export type * from './lib/Search'
export type * from './lib/Section'
export type * from './lib/Select'
export type * from './lib/Small'
export type * from './lib/Source'
export type * from './lib/Span'
export type * from './lib/Strikethrough'
export type * from './lib/Strong'
export type * from './lib/Style'
export type * from './lib/Subscript'
export type * from './lib/Summary'
export type * from './lib/Superscript'
export type * from './lib/Svg'
export type * from './lib/Table'
export type * from './lib/TableBody'
export type * from './lib/TableData'
export type * from './lib/TableFooter'
export type * from './lib/TableHead'
export type * from './lib/TableHeader'
export type * from './lib/TableRow'
export type * from './lib/Template'
export type * from './lib/TextArea'
export type * from './lib/Time'
export type * from './lib/Title'
export type * from './lib/Track'
export type * from './lib/Underline'
export type * from './lib/UnorderedList'
export type * from './lib/Variable'
export type * from './lib/Video'
export type * from './lib/WordBreakOpportunity'
