packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.0.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  eslint: ^9.0.0
  jest: ^30.0.2
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.3.3
  vite: ^6.3.5
