packages:
  - apps/*
  - packages/*

catalog:
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/node": ^24.0.4
  "@types/react-dom": ^19.1.6
  "@types/react": ^19.1.8
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  bunchee: ^6.5.4
  eslint: ^9.30.1
  jsdom: ^26.1.0
  prettier: ^3.6.2
  react-dom: ^19.1.0
  react: ^19.1.0
  next: ^15.3.5
  rimraf: ^6.0.1
  tsup: ^8.5.0
  nodemon: ^3.1.9
  tsx: ^4.19.3
  tslib: ^2.8.1
  typescript: ^5.8.3
  tsconfig-paths: ^4.2.0
  vite-plugin-devtools-json: ^0.2.0
  vite: ^6.3.5
  vitest: ^3.2.4
