export { default as ArticleLayout } from '@/components/layouts/Article'
export { default as FooterLayout } from '@/components/layouts/Footer'
export { default as HeaderLayout } from '@/components/layouts/Header'
export { default as NewsletterLayout } from '@/components/layouts/Newsletter'
export { default as PhotosLayout } from '@/components/layouts/Photos'
export { default as ResumeLayout } from '@/components/layouts/Resume'
export { default as SimpleLayout } from '@/components/layouts/Simple'
