export { default as logoDjango } from './logos/django.png'
export { default as logoEpicDesignLabs } from './logos/epic-design-labs.png'
export { default as logoGithub } from './logos/github.png'
export { default as logoInfosoftStudio } from './logos/infosoft-studio.png'
export { default as logoMakeDevelopment } from './logos/make-development.jpeg'
export { default as logoMultiplyMii } from './logos/multiplymii.jpeg'
export { default as logoNpm } from './logos/npm.png'
export { default as logoReact } from './logos/react.png'
export { default as logoWordPress } from './logos/wordpress.png'
export { default as logoXTeam } from './logos/x-team.png'

export { default as photoFood } from './photos/food.jpg'
export { default as photoPhotography } from './photos/photography.jpg'
export { default as photoSpeaker } from './photos/speaker.jpg'
export { default as photoTravel } from './photos/travel.jpg'
export { default as photoWorkplace } from './photos/workplace.jpg'

export { default as imageAvatar } from './avatar.jpg'
export { default as imagePortrait } from './portrait.jpg'
